-- ============================================================
-- LAB COMPLAINT PORTAL
-- DATABASE SETUP
-- ============================================================


-- ============================================================
-- 1. COMPLAINTS TABLE
-- ============================================================

create table if not exists public.complaints (

    id bigint generated by default as identity primary key,

    student_name text not null,

    board_roll_number text not null,

    lab_room_number integer not null,

    system_number integer not null,

    complaint text not null,

    created_at timestamptz
        not null
        default now(),

    status text
        not null
        default 'OPEN',

    fixed_at timestamptz null,


    constraint valid_lab_room
        check (
            lab_room_number in (103, 115, 121)
        ),


    constraint valid_system_number
        check (
            system_number between 01 and 99
        ),


    constraint valid_status
        check (
            status in ('OPEN', 'FIXED')
        )

);


-- ============================================================
-- 2. ADMIN TABLE
-- ============================================================

create table if not exists public.admins (

    user_id uuid primary key
        references auth.users(id)
        on delete cascade,

    created_at timestamptz
        not null
        default now()

);


-- ============================================================
-- 3. INDEXES
-- ============================================================

create index if not exists complaints_lab_index
on public.complaints(lab_room_number);


create index if not exists complaints_status_index
on public.complaints(status);


create index if not exists complaints_created_index
on public.complaints(created_at);


create index if not exists complaints_fixed_index
on public.complaints(fixed_at);


-- ============================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table public.complaints
enable row level security;


alter table public.admins
enable row level security;


-- ============================================================
-- 5. STUDENT INSERT POLICY
--
-- Students do not need an account.
-- They can create complaints.
-- ============================================================

drop policy if exists
"Anyone can submit complaints"
on public.complaints;


create policy
"Anyone can submit complaints"

on public.complaints

for insert

to anon, authenticated

with check (

    lab_room_number in (103, 115, 121)

    and

    system_number between 01 and 99

    and

    status = 'OPEN'

);


-- ============================================================
-- 6. ADMIN READ POLICY
-- ============================================================

drop policy if exists
"Admins can view complaints"
on public.complaints;


create policy
"Admins can view complaints"

on public.complaints

for select

to authenticated

using (

    exists (
        select 1

        from public.admins

        where admins.user_id =
              auth.uid()
    )

);


-- ============================================================
-- 7. ADMIN UPDATE POLICY
-- ============================================================

drop policy if exists
"Admins can update complaints"
on public.complaints;


create policy
"Admins can update complaints"

on public.complaints

for update

to authenticated

using (

    exists (
        select 1

        from public.admins

        where admins.user_id =
              auth.uid()
    )

)

with check (

    exists (
        select 1

        from public.admins

        where admins.user_id =
              auth.uid()
    )

);


-- ============================================================
-- 8. ADMIN DELETE POLICY
-- ============================================================

drop policy if exists
"Admins can delete complaints"
on public.complaints;


create policy
"Admins can delete complaints"

on public.complaints

for delete

to authenticated

using (

    exists (
        select 1

        from public.admins

        where admins.user_id =
              auth.uid()
    )

);


-- ============================================================
-- 9. ADMIN TABLE SECURITY
-- ============================================================

drop policy if exists
"Admins can view their own admin record"
on public.admins;


create policy
"Admins can view their own admin record"

on public.admins

for select

to authenticated

using (
    user_id = auth.uid()
);


-- ============================================================
-- 10. AUTOMATIC DELETION OF FIXED COMPLAINTS
--
-- Fixed complaints older than 7 days are removed.
-- ============================================================


-- Enable pg_cron if available.

create extension if not exists pg_cron;


-- Remove an existing job with this name if present.

select cron.unschedule(
    jobid
)
from cron.job
where jobname =
      'delete-old-fixed-complaints';


-- Create the automatic cleanup job.

select cron.schedule(
    'delete-old-fixed-complaints',

    '0 0 * * *',

    $$
        delete from public.complaints

        where status = 'FIXED'

        and fixed_at is not null

        and fixed_at <=
            now() - interval '7 days';
    $$
);